//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace SMADA_2012.App_Code.SMADA
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/PollutantLandUse.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/PollutantLandUse.xsd", IsNullable = false)]
    public partial class landUses
    {

        private landUsesLandUse landUseField;

        /// <remarks/>
        public landUsesLandUse landUse
        {
            get
            {
                return this.landUseField;
            }
            set
            {
                this.landUseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/PollutantLandUse.xsd")]
    public partial class landUsesLandUse
    {

        private string landUseNameField;

        private float rationalCField;

        private landUsesLandUsePollutant pollutantField;

        /// <remarks/>
        public string landUseName
        {
            get
            {
                return this.landUseNameField;
            }
            set
            {
                this.landUseNameField = value;
            }
        }

        /// <remarks/>
        public float rationalC
        {
            get
            {
                return this.rationalCField;
            }
            set
            {
                this.rationalCField = value;
            }
        }

        /// <remarks/>
        public landUsesLandUsePollutant pollutant
        {
            get
            {
                return this.pollutantField;
            }
            set
            {
                this.pollutantField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/PollutantLandUse.xsd")]
    public partial class landUsesLandUsePollutant
    {

        private string pollutantNameField;

        private float pollutantConcentrationField;

        /// <remarks/>
        public string pollutantName
        {
            get
            {
                return this.pollutantNameField;
            }
            set
            {
                this.pollutantNameField = value;
            }
        }

        /// <remarks/>
        public float pollutantConcentration
        {
            get
            {
                return this.pollutantConcentrationField;
            }
            set
            {
                this.pollutantConcentrationField = value;
            }
        }
    }
}
