//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMADA_2012.SMADAForms {
    
    
    public partial class CalculateTimeOfConcentration {
        
        /// <summary>
        /// ucTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SMADA_2012.UserControls.ucTimeOfConcentration ucTC;
    }
}
